site_name: AnyDI
site_description: Dependency Injection library
site_author: Anton Ruhlov
site_url: https://github.com/antonrh/anydi

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: antonrh/anydi
repo_url: https://github.com/antonrh/anydi
edit_uri: ""

nav:
  - Home: index.md
  - Core Concepts: concepts.md
  - Usage Guide:
    - Providers:
      - Overview: usage/providers/index.md
      - Basics: usage/providers/basics.md
      - Named Providers: usage/providers/annotated.md
      - Resource Management: usage/providers/resources.md
      - Auto-Registration: usage/providers/auto-registration.md
    - Scopes: usage/scopes.md
    - Dependency Injection: usage/injection.md
    - Modules: usage/modules.md
    - Testing: usage/testing.md
  - Extensions:
    - FastAPI: extensions/fastapi.md
    - FastStream: extensions/faststream.md
    - Typer: extensions/typer.md
    - Pydantic Settings: extensions/pydantic_settings.md
    - Django: extensions/django.md
  - Examples:
    - Basic Application: examples/basic.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
